name: risuai

services:
  risuai:
    container_name: risuai
    image: ghcr.io/kwaroran/risuai:latest
    restart: always
    ports:
      - 6001:6001
    volumes:
      - /volume2/docker/risusave:/app/save
